const universities = [
  { id:'stanford', name:'Stanford', country:'United States', location:'California', short:'S', category:'Reach', major:'CS alignment', reason:'Your clear CS direction and leadership story are relevant. The bar is exceptionally high, so depth and evidence matter.', gaps:['English score','STEM project depth','Application preparation'], tuition:'$65k+ / year', aid:'Need-aware', deadline:'Jan 05, 2027', route:'Common App', language:'IELTS 7.0+', sources:['admission.stanford.edu','financialaid.stanford.edu'] },
  { id:'mit', name:'MIT', country:'United States', location:'Cambridge, MA', short:'M', category:'Reach', major:'CS + STEM fit', reason:'Your STEM ambition is pointed in the right direction. A substantial technical project would make the story more legible.', gaps:['Research depth','Testing strategy','Application preparation'], tuition:'$63k+ / year', aid:'Need-blind*', deadline:'Jan 04, 2027', route:'Common App', language:'IELTS 7.0+', sources:['mit.edu/admissions','sfs.mit.edu'] },
  { id:'nus', name:'National University of Singapore', country:'Singapore', location:'Kent Ridge', short:'N', category:'Target', major:'Computing fit', reason:'Strong academic direction and international ambition line up with a focused computing application.', gaps:['IELTS score','Math evidence'], tuition:'S$18k+ / year', aid:'Limited', deadline:'Feb 28, 2027', route:'Direct application', language:'IELTS 6.5+', sources:['nus.edu.sg/oam','nus.edu.sg/financial-aid'] },
  { id:'purdue', name:'Purdue University', country:'United States', location:'West Lafayette, IN', short:'P', category:'Target', major:'CS fit', reason:'A practical CS route where your current academic profile has a clearer point of entry.', gaps:['English score','Project portfolio'], tuition:'$42k+ / year', aid:'Merit-based', deadline:'Jan 15, 2027', route:'Common App', language:'IELTS 6.5+', sources:['admissions.purdue.edu'] },
  { id:'nu', name:'Nazarbayev University', country:'Kazakhstan', location:'Astana', short:'NU', category:'Strong Fit', major:'CS + local fit', reason:'English-medium STEM study close to home, with a strong platform for research, startups, and a global next step.', gaps:['Application preparation','Project depth'], tuition:'Demo data: verify', aid:'Scholarships available*', deadline:'Demo: verify cycle', route:'Direct application', language:'IELTS 6.5+', sources:['nu.edu.kz/admissions'] },
  { id:'kbtu', name:'KBTU', country:'Kazakhstan', location:'Almaty', short:'K', category:'Strong Fit', major:'IT fit', reason:'A local technical route that keeps costs and geography manageable while you build evidence of your interests.', gaps:['Portfolio depth'], tuition:'Demo data: verify', aid:'Demo: verify', deadline:'Demo: verify cycle', route:'Direct application', language:'IELTS 6.0+', sources:['kbtu.edu.kz'] }
];
const opportunities = [
  { icon:'<>', name:'AI / Robotics Hackathon', category:'Hackathon', country:'Online + local', deadline:'Oct 18, 2026', why:'Turns your CS interest into a visible technical project with a story you can keep developing.', skills:'Build • Iterate • Ship' },
  { icon:'//', name:'Student Research Sprint', category:'Research', country:'Online', deadline:'Nov 02, 2026', why:'Adds research depth to your profile and lets you test which part of computing you actually enjoy.', skills:'Question • Analyze • Present' },
  { icon:'∑', name:'Mathematics / Informatics League', category:'Competition', country:'Kazakhstan', deadline:'Dec 12, 2026', why:'A focused way to strengthen evidence of mathematical thinking for STEM programs.', skills:'Logic • Speed • Precision' },
  { icon:'↗', name:'Astana Hub Youth Program', category:'Entrepreneurship', country:'Astana', deadline:'Rolling', why:'Build locally and think globally: turn a student problem into a small product or pilot.', skills:'Founder • Customer • Impact' },
  { icon:'+', name:'Community Tech Volunteer Lab', category:'Community', country:'Almaty', deadline:'Monthly', why:'Gives your existing leadership and volunteering a measurable STEM direction.', skills:'Lead • Teach • Measure' },
  { icon:'[]', name:'Open Source Starter Month', category:'Project', country:'Online', deadline:'Rolling', why:'A low-barrier path to a public project, consistent contributions, and a stronger portfolio.', skills:'Code • Collaborate • Document' }
];

const state = { view:'overview', selectedUni:'stanford', saved:['stanford','nu'], selectedOpportunities:[], sat:1380, ielts:6.5, profileStrength:'Current', actionDone:false, onboarding:false, onboardStep:0 };
const app = document.querySelector('#app');
const navItems = [['overview','Dashboard','01'],['map','Universities','02'],['opportunities','Opportunities','03'],['compare','Compare','04'],['roadmap','Roadmap','05']];
const uni = id => universities.find(item => item.id === id) || universities[0];
const initials = name => name.split(' ').map(word => word[0]).join('').slice(0,2);

const ru = [
  ['ADMISSION STRATEGY SYSTEM', 'СИСТЕМА СТРАТЕГИИ ПОСТУПЛЕНИЯ'],
  ['Your future is not a list.', 'Ваше будущее — это не список.'],
  ['It’s a ', 'Это '], ['route.', 'маршрут.'],
  ['It’s a route.', 'Это маршрут.'],
  ['For the next version of you', 'Для следующей версии вас'],
  ['NAVI turns your profile, ambitions, and constraints into a personalized university admission journey.', 'QMAP превращает ваш профиль, цели и ограничения в персональный путь к поступлению в университет.'],
  ['Dreams', 'Мечты'], ['Grade 10', '10 класс'], ['Grade 10 · Kazakhstan', '10 класс · Казахстан'], ['Computer Science', 'Компьютерные науки'],
  ['Build my admission map', 'Создать мою карту поступления'],
  ['Takes ~3 minutes', 'Займёт около 3 минут'],
  ['your route', 'ваш маршрут'],
  ['where you start', 'с чего вы начинаете'],
  ['where you want to go', 'куда вы хотите прийти'],
  ['how you grow', 'как вы развиваетесь'],
  ['what to do next', 'что делать дальше'],
  ['PROFILE → GAPS → OPPORTUNITIES → IMPROVEMENT', 'ПРОФИЛЬ → ПРОБЕЛЫ → ВОЗМОЖНОСТИ → РОСТ'],
  ['DEMO PROFILE · KAZAKHSTAN', 'ДЕМО-ПРОФИЛЬ · КАЗАХСТАН'],
  ['Dashboard', 'Обзор'], ['Universities', 'Университеты'], ['Opportunities', 'Возможности'], ['Compare', 'Сравнение'], ['Roadmap', 'План действий'],
  ['Profile', 'Профиль'], ['Good morning, Amina.', 'Доброе утро, Амина.'], ['Your admission strategy', 'Ваша стратегия поступления'],
  ['Your route is taking shape. You have strong momentum in leadership and a clear CS direction. The next unlock is depth.', 'Ваш маршрут формируется. У вас сильная база в лидерстве и ясный интерес к компьютерным наукам. Следующий шаг — развить глубину.'],
  ['Profile 68% ready', 'Профиль готов на 68%'], ['Your profile at a glance', 'Ваш профиль вкратце'], ['STEM-focused international applicant', 'Международный абитуриент с фокусом на STEM'],
  ['graduating 2028', 'выпуск в 2028 году'], ['Dream university', 'Университет мечты'], ['Your chosen north star shapes this strategy.', 'Выбранная цель задаёт эту стратегию.'],
  ['Strong mathematics', 'Сильная математика'], ['Leadership experience', 'Опыт лидерства'], ['Today’s signal', 'Сигнал на сегодня'], ['Updated just now', 'Только что обновлено'],
  ['Strength', 'Сильная сторона'], ['Gap to close', 'Что нужно улучшить'], ['Next move', 'Следующий шаг'], ['Clear direction', 'Чёткое направление'],
  ['Your interest in CS is consistent across academics and activities.', 'Ваш интерес к компьютерным наукам проявляется и в учёбе, и во внеклассных занятиях.'],
  ['STEM depth', 'Глубина STEM-профиля'], ['One substantial project would make your profile more memorable.', 'Один серьёзный проект сделает ваш профиль заметнее.'],
  ['Take IELTS diagnostic', 'Пройдите диагностический тест IELTS'], ['A baseline helps you set a precise 7.0+ target.', 'Базовый результат поможет поставить точную цель 7.0+.'],
  ['Your route, in motion', 'Ваш маршрут в движении'], ['connected steps', 'связанных шага'], ['Understand your gaps', 'Понять свои пробелы'], ['Diagnosis complete', 'Диагностика завершена'],
  ['Build evidence', 'Собрать подтверждения'], ['Opportunities selected', 'Возможности выбраны'], ['Widen your options', 'Расширить выбор'], ['What-if ready', 'Симулятор готов'],
  ['Your Admission Map', 'Ваша карта поступления'], ['Profile → gaps → options', 'Профиль → пробелы → варианты'], ['Try what-if', 'Попробовать сценарий'],
  ['Guidance based on your current profile and published program information. These are fit categories, never admission predictions.', 'Рекомендации основаны на вашем профиле и опубликованной информации о программах. Это категории соответствия, а не прогноз решения о зачислении.'],
  ['routes worth exploring', 'маршрутов для изучения'], ['Dream list:', 'Список мечты:'], ['Reach', 'Высокая конкуренция'], ['Target', 'Целевой вариант'], ['Strong Fit', 'Сильное соответствие'], ['Major', 'Направление'], ['Watch', 'Внимание'], ['Explore', 'Открыть'],
  ['University lens', 'Фокус на университете'], ['What this route could mean for you, and what to verify next.', 'Что этот маршрут может значить для вас и что проверить дальше.'], ['Back to map', 'Назад к карте'], ['Save to dream list', 'Сохранить в список мечты'], ['Saved to dream list', 'Сохранено в список мечты'],
  ['Application route', 'Способ подачи'], ['Tuition', 'Стоимость обучения'], ['Financial aid', 'Финансовая помощь'], ['Deadline', 'Дедлайн'], ['Language', 'Языковые требования'], ['Graduation', 'Выпуск'], ['Official admissions page', 'Официальная страница приёма'], ['Verify current cycle', 'Проверьте для текущего цикла'], ['Official aid information', 'Официальная информация о помощи'], ['Verify before applying', 'Проверьте перед подачей'], ['Program requirements', 'Требования программы'], ['Your profile', 'Ваш профиль'],
  ['Why QMAP matched you', 'Почему QMAP подобрал этот вариант'], ['Interpretation', 'Интерпретация'], ['Your gaps', 'Ваши пробелы'], ['Actionable', 'Что делать'], ['What does', 'Что ценит'], ['Published information', 'Опубликованная информация'],
  ['Opportunities for you', 'Возможности для вас'], ['Dream university → profile gap → opportunity', 'Университет мечты → пробел профиля → возможность'], ['Not a catalog. These six options were selected because they help close your current gaps: English confidence, STEM depth, and measurable impact.', 'Это не каталог. Эти возможности выбраны, потому что помогают закрыть ваши пробелы: английский, глубина STEM и измеримый вклад.'],
  ['relevant routes', 'подходящих маршрутов'], ['Because Stanford is on your list', 'Потому что Stanford есть в вашем списке'], ['Current gap: deeper STEM evidence', 'Текущий пробел: больше STEM-подтверждений'], ['Build locally. Think globally.', 'Развивайтесь локально. Думайте глобально.'], ['Possible routes, not recommendations', 'Возможные маршруты, не рекомендации'],
  ['Compare routes', 'Сравнить маршруты'], ['Make differences visible', 'Сделать различия заметными'], ['Comparison is here to clarify trade-offs, not decide which university is better.', 'Сравнение помогает увидеть компромиссы, но не решает, какой университет лучше.'], ['Key trade-offs', 'Главные компромиссы'], ['Keep your constraints visible', 'Учитывайте свои ограничения'],
  ['Your Admission Roadmap', 'Ваш план поступления'], ['Your route, made actionable', 'Ваш маршрут, превращённый в действия'], ['Generated from your graduation timeline, target universities, profile gaps, and selected opportunities.', 'План создан на основе года выпуска, целевых университетов, пробелов профиля и выбранных возможностей.'], ['Graduating 2028', 'Выпуск в 2028 году'], ['Timeline', 'Таймлайн'], ['Your next action', 'Ваше следующее действие'], ['Dream list', 'Список мечты'], ['Mark as done', 'Отметить выполненным'], ['Shortlist 3 STEM opportunities', 'Выбрать 3 STEM-возможности'], ['Take an IELTS diagnostic test this week.', 'Пройдите диагностический тест IELTS на этой неделе.'],
  ['Your profile', 'Ваш профиль'], ['Amina’s admission profile', 'Профиль Амины для поступления'], ['The inputs QMAP uses to connect diagnosis, universities, opportunities, and roadmap.', 'Данные, которые QMAP использует для связи диагностики, университетов, возможностей и плана.'], ['Education', 'Образование'], ['Intended major', 'Желаемое направление'], ['Academics', 'Учёба'], ['Strong GPA', 'Высокий средний балл'], ['Strongest subjects:', 'Сильнейшие предметы:'], ['Budget', 'Бюджет'], ['Aid essential', 'Финансовая помощь необходима'], ['Activities', 'Активности'], ['Evidence over volume', 'Качество важнее количества'], ['Leadership', 'Лидерство'], ['Community', 'Сообщество'], ['Sports', 'Спорт'],
  ['What if I improve?', 'Что, если я улучшу профиль?'], ['Scenario planning', 'Сценарное планирование'], ['Explore how stronger inputs may make additional options relevant. This is not an admission probability calculator.', 'Посмотрите, как улучшение показателей может открыть новые варианты. Это не калькулятор вероятности поступления.'], ['Adjust your scenario', 'Измените сценарий'], ['Hypothetical', 'Гипотеза'], ['Extracurricular profile', 'Внеклассный профиль'], ['Current', 'Текущий'], ['Stronger', 'Усиленный'], ['Map impact', 'Влияние на карту'], ['Guidance, not prediction', 'Рекомендация, не прогноз'], ['BEFORE', 'ДО'], ['AFTER', 'ПОСЛЕ'], ['New options may become relevant', 'Могут стать актуальны новые варианты'],
  ['Build your admission map', 'Создайте карту поступления'], ['Setup', 'Настройка'], ['Where are you in your education?', 'На каком этапе образования вы находитесь?'], ['The school system matters because the same grade can mean different stages in different countries.', 'Школьная система важна: один и тот же класс может означать разные этапы в разных странах.'], ['What do you want to study?', 'Что вы хотите изучать?'], ['Choose a dream university', 'Выберите университет мечты'], ['What should QMAP focus on first?', 'На чём QMAP должен сосредоточиться в первую очередь?'], ['A few high-signal inputs are enough to start your route.', 'Нескольких важных ответов достаточно, чтобы начать ваш маршрут.'], ['Continue', 'Продолжить'], ['See my map', 'Посмотреть мою карту'], ['Return', 'Вернуться'], ['Back', 'Назад'], ['Improve IELTS', 'Улучшить IELTS'], ['Build a STEM project', 'Создать STEM-проект'], ['Explore funding', 'Изучить финансирование'], ['All of the above', 'Всё перечисленное'],
  ['Grade 9', '9 класс'], ['Grade 11', '11 класс'], ['Grade 12', '12 класс'], ['of 04', 'из 04'], ['NAVI / overview', 'QMAP / обзор'], ['NAVI / map', 'QMAP / университеты'], ['NAVI / opportunities', 'QMAP / возможности'], ['NAVI / compare', 'QMAP / сравнение'], ['NAVI / roadmap', 'QMAP / план действий'],
  ['United States', 'США'], ['Singapore', 'Сингапур'], ['Kazakhstan', 'Казахстан'], ['Online + local', 'Онлайн + локально'], ['Online', 'Онлайн'], ['Astana', 'Астана'], ['Almaty', 'Алматы'], ['Rolling', 'Постоянный набор'],
  ['Hackathon', 'Хакатон'], ['Research', 'Исследования'], ['Competition', 'Соревнование'], ['Entrepreneurship', 'Предпринимательство'], ['Community', 'Сообщество'], ['Project', 'Проект'], ['Current gap', 'Текущий пробел'], ['Route 01', 'Маршрут 01'], ['Route 02', 'Маршрут 02'], ['Now', 'Сейчас'], ['Next', 'Далее'], ['This year', 'В этом году'], ['Application season', 'Период подачи'],
  ['Current', 'Текущий'], ['Stronger', 'Усиленный'], ['BEFORE', 'ДО'], ['AFTER', 'ПО'], ['Профиль 68% ready', 'Профиль готов на 68%'], ['Open my admission map', 'Открыть мою карту поступления'], ['now', 'сейчас'], ['next', 'далее'], ['later', 'позже'], ['selected', 'выбраны'],
  ['A few high-signal inputs are enough to start your маршрут.', 'Нескольких важных ответов достаточно, чтобы начать ваш маршрут.'], ['A few high-signal inputs are enough to start your route.', 'Нескольких важных ответов достаточно, чтобы начать ваш маршрут.'], ['This choice becomes the lens for your diagnosis, opportunities, and roadmap.', 'Этот выбор станет основой для диагностики, возможностей и плана действий.'], ['What should QMAP focus on first?', 'На чём QMAP должен сосредоточиться в первую очередь?'], ['What should NAVI focus on first?', 'На чём QMAP должен сосредоточиться в первую очередь?'], ['funding', 'финансирование'], ['Engineering', 'Инженерия'], ['Business', 'Бизнес'], ['Economics', 'Экономика'],
  ['CS alignment', 'Соответствие компьютерным наукам'], ['CS + STEM fit', 'Соответствие CS и STEM'], ['Computing fit', 'Соответствие вычислительным наукам'], ['CS fit', 'Соответствие CS'], ['CS + local fit', 'Соответствие CS и локальному маршруту'], ['IT fit', 'Соответствие IT'],
  ['Your clear CS direction and leadership story are relevant. The bar is exceptionally high, so depth and evidence matter.', 'Ваш ясный интерес к CS и опыт лидерства релевантны. Конкуренция очень высокая, поэтому важны глубина и подтверждения.'], ['Your STEM ambition is pointed in the right direction. A substantial technical project would make the story more legible.', 'Ваш интерес к STEM развивается в правильном направлении. Серьёзный технический проект сделает профиль убедительнее.'], ['Strong academic direction and international ambition line up with a focused computing application.', 'Сильная академическая база и международные цели хорошо сочетаются с заявкой на вычислительное направление.'], ['A practical CS route where your current academic profile has a clearer point of entry.', 'Практичный маршрут в CS, где вашему текущему академическому профилю проще найти точку входа.'], ['English-medium STEM study close to home, with a strong platform for research, startups, and a global next step.', 'Обучение STEM на английском рядом с домом и сильная платформа для исследований, стартапов и глобального следующего шага.'], ['A local technical route that keeps costs and geography manageable while you build evidence of your interests.', 'Локальный технический маршрут с доступными расходами и географией, пока вы подтверждаете свои интересы.'],
  ['English score', 'Результат по английскому'], ['STEM project depth', 'Глубина STEM-проектов'], ['Application preparation', 'Подготовка заявки'], ['Research depth', 'Глубина исследований'], ['Testing strategy', 'Стратегия тестирования'], ['IELTS score', 'Результат IELTS'], ['Math evidence', 'Подтверждение математики'], ['Project portfolio', 'Портфолио проектов'], ['Project depth', 'Глубина проектов'], ['Portfolio depth', 'Глубина портфолио'], ['Need-aware', 'Помощь зависит от финансовой необходимости'], ['Need-blind*', 'Без учёта финансовой необходимости*'], ['Limited', 'Ограниченная'], ['Merit-based', 'На основе достижений'], ['Scholarships available*', 'Доступны стипендии*'], ['Demo data: verify', 'Демо-данные: проверьте'], ['Demo: verify cycle', 'Демо: проверьте цикл'], ['Common App', 'Common App'], ['Direct application', 'Прямая заявка'],
  ['Turns your CS interest into a visible technical project with a story you can keep developing.', 'Превращает ваш интерес к CS в заметный технический проект, который можно развивать дальше.'], ['Adds research depth to your profile and lets you test which part of computing you actually enjoy.', 'Добавляет исследовательскую глубину и помогает понять, какая область вычислений вам действительно интересна.'], ['A focused way to strengthen evidence of mathematical thinking for STEM programs.', 'Целенаправленный способ усилить подтверждения математического мышления для STEM-программ.'], ['Build locally and think globally: turn a student problem into a small product or pilot.', 'Развивайтесь локально и думайте глобально: превратите проблему студента в небольшой продукт или пилот.'], ['Gives your existing leadership and volunteering a measurable STEM direction.', 'Придаёт вашему лидерству и волонтёрству измеримое STEM-направление.'], ['A low-barrier path to a public project, consistent contributions, and a stronger portfolio.', 'Доступный путь к публичному проекту, регулярным вкладам и более сильному портфолио.'], ['Build • Iterate • Ship', 'Создать • Улучшить • Запустить'], ['Question • Analyze • Present', 'Исследовать • Проанализировать • Представить'], ['Logic • Speed • Precision', 'Логика • Скорость • Точность'], ['Founder • Customer • Impact', 'Основатель • Пользователь • Влияние'], ['Lead • Teach • Measure', 'Вести • Обучать • Измерять'], ['Code • Collaborate • Document', 'Кодить • Сотрудничать • Документировать'], ['AI / Robotics Hackathon', 'Хакатон по AI и робототехнике'], ['Student Research Sprint', 'Исследовательский спринт для студентов'], ['Mathematics / Informatics League', 'Лига математики и информатики'], ['Astana Hub Youth Program', 'Молодёжная программа Astana Hub'], ['Community Tech Volunteer Lab', 'Волонтёрская лаборатория технологий'], ['Open Source Starter Month', 'Месяц открытого исходного кода'], ['Oct 18, 2026', '18 октября 2026'], ['Nov 02, 2026', '2 ноября 2026'], ['Dec 12, 2026', '12 декабря 2026'], ['Monthly', 'Каждый месяц'], ['Source Starter Month', 'Месяц открытого исходного кода']
];
function translateText(text) {
  const translated = ru.reduce((result, [from, to]) => result.replaceAll(from, to), text);
  return translated
    .replaceAll('Open my admission map →', 'Открыть мою карту поступления →')
    .replaceAll('Профиль 68% ready', 'Профиль готов на 68%')
    .replaceAll('Common App', 'Общее приложение')
    .replaceAll('University lens', 'Профиль университета')
    .replaceAll('Open', 'Открыть')
    .replaceAll('saved', 'сохранено')
    .replaceAll('AI / Robotics Хакатон', 'Хакатон по искусственному интеллекту и робототехнике')
    .replaceAll('Student Исследования Sprint', 'Исследовательский спринт для студентов')
    .replaceAll('Астана Hub Youth Program', 'Молодёжная программа Астана Хаб')
    .replaceAll('Сообщество Tech Volunteer Lab', 'Лаборатория технологического волонтёрства')
    .replaceAll('AI', 'ИИ')
    .replaceAll('CS', 'компьютерные науки')
    .replaceAll('STEM', 'естественно-научный профиль');
}

function localize(markup) {
  return markup.replace(/>([^<>]+)</g, (match, text) => `>${translateText(text)}<`);
}

function render() { app.innerHTML = localize(state.onboarding ? renderOnboarding() : renderShell()).replaceAll('NAVI', 'QMAP').replaceAll('class="brand-mark">N', 'class="brand-mark">Q'); bindEvents(); }
function renderShell() { return `<div class="dashboard-shell"><aside class="sidebar"><div class="brand"><span class="brand-mark">N</span>NAVI</div><nav class="nav-list">${navItems.map(([id,label,num])=>`<button class="nav-item ${state.view===id?'active':''}" data-view="${id}"><span class="nav-icon">${num}</span><span>${label}</span></button>`).join('')}</nav><div class="profile-chip"><div class="avatar">AM</div><div><strong>Amina M.</strong><small>Grade 10 · Kazakhstan</small></div></div></aside><main class="main"><div class="topbar"><span class="breadcrumb">NAVI / ${state.view}</span><button class="ghost-button" data-view="profile">Profile ↗</button></div>${renderView()}</main></div>`; }
function renderView() { return ({overview:renderOverview,map:renderMap,opportunities:renderOpportunities,compare:renderCompare,roadmap:renderRoadmap,profile:renderProfile,detail:renderDetail,simulator:renderSimulator}[state.view] || renderOverview)(); }
function renderOverview() { return `<div class="page-head fade-in"><div><span class="eyebrow">Your admission strategy</span><h1>Good morning, Amina.</h1><p>Your route is taking shape. You have strong momentum in leadership and a clear CS direction. The next unlock is depth.</p></div><span class="pill pill-target">Profile 68% ready</span></div><section class="overview-hero fade-in"><div class="welcome-card"><span class="eyebrow">Your profile at a glance</span><h2>STEM-focused international applicant</h2><p>Grade 10 · Kazakhstan · Computer Science · graduating 2028</p><button class="primary-button" data-view="map">Open my admission map →</button></div><div class="panel stat-card"><div><span class="kicker">Dream university</span><div class="stat-value">Stanford</div><span class="stat-caption">Your chosen north star shapes this strategy.</span></div><div><div class="signal-row"><i class="signal-dot good"></i> Strong mathematics</div><div class="signal-row"><i class="signal-dot good"></i> Leadership experience</div><div class="signal-row"><i class="signal-dot watch"></i> IELTS 6.5</div></div></div></section><div class="section-label"><h2>Today’s signal</h2><span>Updated just now</span></div><section class="grid-3 fade-in"><div class="panel panel-pad"><span class="kicker">Strength</span><div class="card-title">Clear direction</div><p class="muted">Your interest in CS is consistent across academics and activities.</p></div><div class="panel panel-pad"><span class="kicker">Gap to close</span><div class="card-title">STEM depth</div><p class="muted">One substantial project would make your profile more memorable.</p></div><div class="panel panel-pad"><span class="kicker">Next move</span><div class="card-title">Take IELTS diagnostic</div><p class="muted">A baseline helps you set a precise 7.0+ target.</p></div></section><div class="section-label"><h2>Your route, in motion</h2><span>4 connected steps</span></div><section class="panel route fade-in"><div class="route-step"><span class="kicker">01 / now</span><strong>Understand your gaps</strong><span>Diagnosis complete</span></div><div class="route-arrow">→</div><div class="route-step"><span class="kicker">02 / next</span><strong>Build evidence</strong><span>Opportunities selected</span></div><div class="route-arrow">→</div><div class="route-step"><span class="kicker">03 / later</span><strong>Widen your options</strong><span>What-if ready</span></div></section>`; }
function renderMap() { return `<div class="page-head fade-in"><div><span class="eyebrow">Profile → gaps → options</span><h1>Your Admission Map</h1><p>Guidance based on your current profile and published program information. These are fit categories, never admission predictions.</p></div><button class="primary-button" data-view="simulator">Try what-if →</button></div><div class="section-label"><h2>6 routes worth exploring</h2><span>Dream list: ${state.saved.length} saved</span></div><section class="grid-3 fade-in">${universities.map(renderUniversityCard).join('')}</section>`; }
function renderUniversityCard(u) { return `<article class="panel university-card clickable-card" data-detail="${u.id}"><div class="uni-top"><div class="uni-monogram">${u.short}</div><button class="save-button ${state.saved.includes(u.id)?'saved':''}" data-save="${u.id}" aria-label="Сохранить ${u.name}">${state.saved.includes(u.id)?'♥':'♡'}</button></div><div style="margin-top:14px"><span class="pill ${u.category==='Reach'?'pill-reach':u.category==='Target'?'pill-target':'pill-fit'}">${u.category}</span><h3 class="card-title">${u.name}</h3><div class="uni-location">${u.location} · ${u.country}</div></div><p class="uni-reason">${u.reason}</p><div class="uni-detail"><div class="detail-line"><strong>Направление</strong><span>${u.major}</span></div><div class="detail-line"><strong>Внимание</strong><span>${u.gaps[0]}</span></div></div><div class="card-actions"><span class="kicker">${u.tuition}</span><button class="text-button" data-detail="${u.id}">Открыть →</button></div></article>`; }
function renderDetail() { const u=uni(state.selectedUni); return `<div class="page-head fade-in"><div><span class="eyebrow">University lens / ${u.category}</span><h1>${u.name}</h1><p>What this route could mean for you, and what to verify next.</p></div><button class="ghost-button" data-view="map">← Back to map</button></div><section class="detail-hero fade-in"><div class="detail-title"><span class="pill pill-${u.category==='Reach'?'reach':u.category==='Target'?'target':'fit'}">${u.category}</span><h2>${u.name}</h2><p>${u.location}, ${u.country} · ${u.major}</p><div style="margin-top:28px"><button class="primary-button" data-save="${u.id}">${state.saved.includes(u.id)?'Saved to dream list':'Save to dream list'}</button></div></div><div class="fact-grid">${[['Application route',u.route,'Official admissions page'],['Tuition',u.tuition,'Verify current cycle'],['Financial aid',u.aid,'Official aid information'],['Deadline',u.deadline,'Verify before applying'],['Language',u.language,'Program requirements'],['Graduation','2028','Your profile']].map(([a,b,c])=>`<div class="fact"><small>${a}</small><strong>${b}</strong><span class="source">${c} ↗</span></div>`).join('')}</div></section><div class="grid-2"><section class="panel panel-pad"><div class="section-label" style="margin:0"><h2>Why NAVI matched you</h2><span>Interpretation</span></div><ul class="check-list"><li>Computer Science matches your intended field.</li><li>Your leadership and volunteering show initiative.</li><li>Your Kazakhstan base makes NU a useful local comparison.</li><li>Financial planning should stay visible in the decision.</li></ul></section><section class="panel panel-pad"><div class="section-label" style="margin:0"><h2>Your gaps</h2><span>Actionable</span></div><ul class="gap-list">${u.gaps.map(g=>`<li>${g}</li>`).join('')}</ul></section></div><section class="panel panel-pad" style="margin-top:18px"><div class="section-label" style="margin:0"><h2>What does ${u.name} value?</h2><span>Published information → interpreted for you</span></div><p class="muted" style="line-height:1.7;max-width:760px">Based on the university’s published admissions information, academic preparation, intellectual interests, and meaningful involvement are relevant signals to investigate. NAVI interprets those public themes against your profile; it does not claim to know how an admissions committee will decide.</p><div class="op-meta">${u.sources.map(s=>`<span>Source: ${s} ↗</span>`).join('')}</div></section>`; }
function renderOpportunities() { return `<div class="page-head fade-in"><div><span class="eyebrow">Университет мечты → пробел профиля → возможность</span><h1>Возможности для вас</h1><p>Это не каталог. Эти варианты выбраны, чтобы помочь закрыть ваши текущие пробелы: английский, глубину STEM и измеримый вклад.</p></div><span class="pill pill-fit">${state.selectedOpportunities.length} выбрано</span></div><section class="panel panel-pad fade-in"><div class="section-label" style="margin:0"><h2>Потому что Stanford есть в вашем списке</h2><span>Текущий пробел: глубина STEM</span></div><div class="grid-3" style="margin-top:20px">${opportunities.map(o=>`<article class="panel opportunity-card ${state.selectedOpportunities.includes(o.name)?'opportunity-selected':''}"><div class="op-icon">${o.icon}</div><span class="pill pill-target">${o.category}</span><h3>${o.name}</h3><p>${o.why}</p><div class="op-meta"><span>${o.country}</span><span>${o.deadline}</span></div><span class="kicker">${o.skills}</span><button class="opportunity-action" data-opportunity="${o.name}">${state.selectedOpportunities.includes(o.name)?'✓ В плане':'Добавить в план'}</button></article>`).join('')}</div></section><div class="section-label"><h2>Развивайтесь локально. Думайте глобально.</h2><span>Возможные маршруты, не рекомендации</span></div><section class="panel route fade-in"><div class="route-step"><span class="kicker">Маршрут 01</span><strong>Казахстан</strong><span>Создать проект или начать исследование</span></div><div class="route-arrow">↓</div><div class="route-step"><span class="kicker">Далее</span><strong>Бакалавриат за рубежом</strong><span>Подать заявку с более сильными подтверждениями</span></div><div class="route-arrow">↓</div><div class="route-step"><span class="kicker">Маршрут 02</span><strong>Магистратура за рубежом</strong><span>Сохранить этот путь открытым</span></div></section>`; }
function renderCompare() { const a=uni('stanford'), b=uni('nu'); return `<div class="page-head fade-in"><div><span class="eyebrow">Make differences visible</span><h1>Compare routes</h1><p>Comparison is here to clarify trade-offs, not decide which university is better.</p></div></div><section class="panel panel-pad fade-in"><div class="select-row"><select id="compare-a"><option>Stanford</option><option>MIT</option><option>NUS</option></select><select id="compare-b"><option>Nazarbayev University</option><option>Purdue University</option><option>KBTU</option></select></div><table class="compare-table"><thead><tr><th>Dimension</th><th>${a.name}</th><th>${b.name}</th></tr></thead><tbody>${[['Major fit','CS alignment','CS + local fit'],['Location','California, USA','Astana, Kazakhstan'],['Budget fit','Important consideration','More manageable locally'],['Language','IELTS 7.0+','IELTS 6.5+'],['Research','Very strong ecosystem','Strong platform to build'],['Application','Common App · higher complexity','Direct application · simpler route']].map(r=>`<tr><td>${r[0]}</td><td>${r[1]}</td><td>${r[2]}</td></tr>`).join('')}</tbody></table></section><div class="section-label"><h2>Key trade-offs</h2><span>Keep your constraints visible</span></div><section class="grid-2"><div class="panel panel-pad"><span class="kicker">Stanford</span><div class="card-title">International upside, higher complexity</div><p class="muted">A highly ambitious route with strong global exposure, but more financial and application complexity to plan for.</p></div><div class="panel panel-pad"><span class="kicker">Nazarbayev University</span><div class="card-title">Lower geographic barrier, strong platform</div><p class="muted">A local English-language STEM environment where you can build research, startup, and leadership depth.</p></div></section>`; }
function renderRoadmap() { const action=state.actionDone?'Shortlist 3 STEM opportunities':'Take an IELTS diagnostic test this week.'; return `<div class="page-head fade-in"><div><span class="eyebrow">Your route, made actionable</span><h1>Your Admission Roadmap</h1><p>Generated from your graduation timeline, target universities, profile gaps, and selected opportunities.</p></div><span class="pill pill-target">Graduating 2028</span></div><section class="grid-2 fade-in"><div class="panel panel-pad"><div class="section-label" style="margin:0 0 22px"><h2>Timeline</h2><span>2026 → 2028</span></div><div class="roadmap"><div class="road-step"><h3>Now</h3><p>Improve IELTS</p><small>Move from 6.5 toward 7.0+ to widen program eligibility.</small></div><div class="road-step"><h3>Next</h3><p>Prepare SAT strategy</p><small>Use a diagnostic to decide whether 1500 is a useful target.</small></div><div class="road-step"><h3>This year</h3><p>Build one substantial STEM project</p><small>Choose one of the opportunities in your personalized finder.</small></div><div class="road-step"><h3>Application season</h3><p>Applications, essays, recommendations, documents</p><small>Verify each university’s official deadline before submitting.</small></div></div></div><div class="next-action"><span class="eyebrow">Your next action</span><h2>${action}</h2><p>${state.actionDone?'Nice. Your next useful move is to choose three opportunities that could become one meaningful project.':'A quick baseline turns “improve English” into a measurable plan.'}</p><button class="primary-button" data-action>${state.actionDone?'Mark next step done':'✓ Mark as done'}</button></div></section><div class="section-label"><h2>Dream list</h2><span>${state.saved.length} saved routes</span></div><section class="grid-3 fade-in">${state.saved.map(id=>{const u=uni(id);return `<div class="panel panel-pad"><span class="pill pill-${u.category==='Reach'?'reach':u.category==='Target'?'target':'fit'}">${u.category}</span><div class="card-title">${u.name}</div><div class="muted" style="font-size:12px">${u.location} · ${u.major}</div></div>`}).join('')}</section>`; }
function renderProfile() { return `<div class="page-head fade-in"><div><span class="eyebrow">Your profile</span><h1>Amina’s admission profile</h1><p>The inputs NAVI uses to connect diagnosis, universities, opportunities, and roadmap.</p></div><button class="primary-button" data-view="overview">Back to dashboard</button></div><section class="grid-2"><div class="panel panel-pad"><span class="kicker">Education</span><div class="card-title">Grade 10 · 12-year school system</div><p class="muted">Graduating 2028 · Kazakhstan</p><span class="kicker">Intended major</span><div class="card-title">Computer Science</div></div><div class="panel panel-pad"><span class="kicker">Academics</span><div class="card-title">Strong GPA · SAT ${state.sat} · IELTS ${state.ielts}</div><p class="muted">Strongest subjects: Mathematics, Computer Science</p><span class="kicker">Budget</span><div class="card-title">$15k · Aid essential</div></div></section><div class="section-label"><h2>Activities</h2><span>Evidence over volume</span></div><section class="grid-3"><div class="panel panel-pad"><span class="kicker">Leadership</span><div class="card-title">Volunteer club</div><p class="muted">Building initiative and measurable impact.</p></div><div class="panel panel-pad"><span class="kicker">Community</span><div class="card-title">Volunteering</div><p class="muted">A foundation to connect with STEM service.</p></div><div class="panel panel-pad"><span class="kicker">Sports</span><div class="card-title">Volleyball · 3 years</div><p class="muted">Consistency and long-term commitment.</p></div></section>`; }
function renderSimulator() { return `<div class="page-head fade-in"><div><span class="eyebrow">Scenario planning</span><h1>What if I improve?</h1><p>Explore how stronger inputs may make additional options relevant. This is not an admission probability calculator.</p></div><button class="ghost-button" data-view="map">← Back to map</button></div><section class="simulator fade-in"><div class="panel panel-pad"><div class="section-label" style="margin:0"><h2>Adjust your scenario</h2><span>Hypothetical</span></div><div class="slider-row"><div class="slider-label"><span>SAT</span><span class="slider-value">${state.sat}</span></div><input type="range" min="1200" max="1600" step="10" value="${state.sat}" data-slider="sat"></div><div class="slider-row"><div class="slider-label"><span>IELTS</span><span class="slider-value">${state.ielts.toFixed(1)}</span></div><input type="range" min="5.5" max="8" step="0.5" value="${state.ielts}" data-slider="ielts"></div><div class="slider-row"><div class="slider-label"><span>Extracurricular profile</span><span class="slider-value">${state.profileStrength}</span></div><div class="option-grid" style="margin:15px 0 0"><button class="option ${state.profileStrength==='Current'?'selected':''}" data-strength="Current">Current</button><button class="option ${state.profileStrength==='Stronger'?'selected':''}" data-strength="Stronger">Stronger</button></div></div></div><div class="panel panel-pad"><div class="section-label" style="margin:0"><h2>Map impact</h2><span>Guidance, not prediction</span></div><div class="before-after"><div class="score"><small>BEFORE</small><strong>8</strong><span class="muted">relevant routes</span></div><div class="arrow">→</div><div class="score" style="background:#e4f3e9"><small>AFTER</small><strong>${state.sat >= 1480 || state.ielts >= 7 || state.profileStrength==='Stronger' ? '12':'9'}</strong><span class="muted">relevant routes</span></div></div><div class="panel panel-pad" style="background:var(--paper)"><span class="kicker">New options may become relevant</span><div class="card-title">Because your profile now meets additional published criteria.</div><p class="muted">${state.ielts >= 7 ? 'Your language score now clears more published requirements.' : 'Raise IELTS to 7.0+ to expand language eligibility.'} ${state.profileStrength==='Stronger' ? 'A deeper project also strengthens your evidence of technical interest.' : 'A substantial technical project is still the strongest next unlock.'}</p></div></div></section>`; }
function renderOnboarding() { const steps=[['Education','Where are you in your education?',['Grade 9','Grade 10','Grade 11','Grade 12']],['Direction','What do you want to study?',['Computer Science','Engineering','Business','Economics']],['North star','Choose a dream university',['Stanford','MIT','NUS','Nazarbayev University']],['Momentum','What should NAVI focus on first?',['Improve IELTS','Build a STEM project','Explore funding','All of the above']]]; const s=steps[state.onboardStep]; return `<div class="onboarding"><div class="onboard-wrap"><div class="landing-nav"><div class="brand"><span class="brand-mark">N</span>NAVI</div><span class="nav-note">Setup / ${String(state.onboardStep+1).padStart(2,'0')} of 04</span></div><div class="progress-bar">${steps.map((_,i)=>`<span class="${i<=state.onboardStep?'active':''}"></span>`).join('')}</div><div class="onboard-question fade-in"><span class="eyebrow">Build your admission map</span><h1>${s[1]}</h1><p>${state.onboardStep===0?'The school system matters because the same grade can mean different stages in different countries.':state.onboardStep===2?'This choice becomes the lens for your diagnosis, opportunities, and roadmap.':'A few high-signal inputs are enough to start your route.'}</p><div class="option-grid">${s[2].map((o,i)=>`<button class="option ${i===1?'selected':''}" data-onboard-option="${o}">${o}</button>`).join('')}</div></div><div class="onboard-actions"><button class="ghost-button" data-onboard-back>${state.onboardStep===0?'← Return':'← Back'}</button><button class="primary-button" data-onboard-next>${state.onboardStep===3?'See my map →':'Continue →'}</button></div></div></div>`; }
function bindEvents() { document.querySelectorAll('[data-view]').forEach(button=>button.addEventListener('click',()=>{ const target=button.dataset.view; if(target==='profile'||navItems.some(item=>item[0]===target)){state.view=target; render();} else if(target==='simulator'){state.view='simulator'; render();} })); document.querySelectorAll('[data-detail]').forEach(button=>button.addEventListener('click',event=>{event.stopPropagation();state.selectedUni=button.dataset.detail;state.view='detail';render();})); document.querySelectorAll('[data-save]').forEach(button=>button.addEventListener('click',event=>{event.stopPropagation();const id=button.dataset.save;state.saved=state.saved.includes(id)?state.saved.filter(x=>x!==id):[...state.saved,id];render();})); document.querySelectorAll('[data-opportunity]').forEach(button=>button.addEventListener('click',()=>{const name=button.dataset.opportunity;state.selectedOpportunities=state.selectedOpportunities.includes(name)?state.selectedOpportunities.filter(item=>item!==name):[...state.selectedOpportunities,name];render();})); document.querySelectorAll('[data-action]').forEach(button=>button.addEventListener('click',()=>{state.actionDone=true;render();})); document.querySelectorAll('[data-slider]').forEach(input=>input.addEventListener('input',()=>{state[input.dataset.slider]=input.dataset.slider==='ielts'?Number(input.value):Number.parseInt(input.value,10);render();})); document.querySelectorAll('[data-strength]').forEach(button=>button.addEventListener('click',()=>{state.profileStrength=button.dataset.strength;render();})); document.querySelectorAll('[data-onboard-option]').forEach(button=>button.addEventListener('click',()=>{document.querySelectorAll('[data-onboard-option]').forEach(item=>item.classList.remove('selected'));button.classList.add('selected');})); document.querySelector('[data-onboard-next]')?.addEventListener('click',()=>{if(state.onboardStep<3){state.onboardStep+=1;render();}else{state.onboarding=false;state.view='overview';render();}}); document.querySelector('[data-onboard-back]')?.addEventListener('click',()=>{if(state.onboardStep===0){state.onboarding=false;render();}else{state.onboardStep-=1;render();}}); }

app.innerHTML = `<div class="landing"><div class="container landing-inner"><nav class="landing-nav"><div class="brand"><span class="brand-mark">N</span>NAVI</div><span class="nav-note">ADMISSION STRATEGY SYSTEM / 01</span></nav><section class="hero"><div><span class="eyebrow">For the next version of you</span><h1>Your future is not a list.<br>It’s a <span>route.</span></h1><p class="hero-copy">NAVI turns your profile, ambitions, and constraints into a personalized university admission journey.</p><div class="hero-actions"><button class="primary-button" data-start>Build my admission map →</button><span class="small-note">Takes ~3 minutes</span></div></div><div class="hero-map"><div class="map-orbit"></div><div class="map-orbit two"></div><div class="map-center"><div>NAVI<small>your route</small></div></div><div class="map-node node-a">Profile<small>where you start</small></div><div class="map-node node-b">Dreams<small>where you want to go</small></div><div class="map-node node-c">Opportunities<small>how you grow</small></div><div class="map-node node-d">Roadmap<small>what to do next</small></div></div></section><footer class="landing-foot"><span>PROFILE → GAPS → OPPORTUNITIES → IMPROVEMENT</span><span>DEMO PROFILE · KAZAKHSTAN</span></footer></div></div>`;
app.innerHTML = localize(app.innerHTML).replaceAll('NAVI', 'QMAP').replaceAll('class="brand-mark">N', 'class="brand-mark">Q');
document.title = document.title.replace('NAVI', 'QMAP');
document.querySelector('[data-start]').addEventListener('click',()=>{state.onboarding=true;render();});
